excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://danielgrin.github.io
title: danielgrin
tagline: 
description: a sometimes blog of technology, art, leading questions and robust ambivalence
paginate: 10
