excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://danielgrin.github.io
title: danielgrin
tagline: a sometimes blog of technology, art, leading questions and robust ambivalence
description: My awesome new site
paginate: 10